version: '3.8'

services:
    mosquitto:
        container_name: mos1
        image: eclipse-mosquitto:2
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./mosquitto/config:/mosquitto/config
            #- ./mosquitto/data:/mosquitto/data
            #- ./mosquitto/log:/mosquitto/log